### ISSUE TITLE
共同內容移動到同一個 wiki

### ISSUE THREAD

**Issue by yorkxin** [taiwanese-work-in/foreign-country#5]
## Why is this change necessary
- 有些共同內容，例如「離開台灣前可以處理的東西」似乎可以整合在同一個 wiki 裡面，讓各國的 wiki 專注在當地資訊
## Proposed solution
- 新開一個 wiki 放這些資訊，例如「general」。這個副效果是會有 `taiwanese-work.in/general` 的網址
- 或是把 `site` 這個 repo 改成 `general` 或 `meta`，把共同內容放在這個 repo 的 wiki
## Definition of done
- 找到一個大家都喜歡的方法可以放共同內容
## TODO
- [x] repo 更名
- [x] 修改此 repo 的 README 說明
- [x] 整理出共同內容第一版 並更新到 wiki
- [x] 更新所有 wiki 的連結

**Comment by ascendbruce** [comment]
`foreign-country` 如何 XD? `taiwanese-work.in/foreign-country`

**Comment by yorkxin** [comment]
Better than `general`!

**Comment by ascendbruce** [comment]
我目前傾向把這個 `site` 改成 `foreign-country`，原因是
- 這個 repo 已經有一些非 code 的票 (eg #6 )，要拆兩個 repos 的話以後會有不知道開在那邊的問題，不如集中一個 repo
- github list 下去漂漂亮亮

**Comment by ascendbruce** [comment]
rename 已完成

剩下的 TODO 更新在 description 裡

**Comment by ascendbruce** [comment]
開始思考合併後的 wiki 應包含哪些內容
- 銀行相關
- 機場通關流程與搭機注意事項
- 其他各種服務帳號（手機、露天、保險）
- 健保與國民年金
- 手機漫遊
- 證件的時效

**Comment by yorkxin** [comment]
> 機場通關流程與搭機注意事項

如果是工作簽證的話，各國機場流程不一定，考慮到並不是每個人都會遇到「第一次出國就是出國工作」，我認為可以寫成附錄之類的。

此外

> 證件的時效

台胞證我覺得可以提一下，因為只能在台灣或中國大陸辦理。

**Comment by ascendbruce** [comment]
> 台胞證我覺得可以提一下，因為只能在台灣或中國大陸辦理。

同意

> 如果是工作簽證的話，各國機場流程不一定，考慮到並不是每個人都會遇到「第一次出國就是出國工作」，我認為可以寫成附錄之類的。

我是想說反正我已經在新加坡 wiki 寫了，乾脆台灣出國通關流程移過去，到達國家則寫概略即可。一個開 wiki 條目不用錢的概念 (?)

**Comment by yorkxin** [comment]
寫了一些

**Comment by ascendbruce** [comment]
已經把其他想得到的都集中過去了, @chitsaou @wayne5540 @aszx87410 請確認各國 wiki 是否有可以連到共同 wiki 的連結還沒改到的，謝謝！
